import { Theme, ThemeId } from "./types";

export const THEMES: Record<ThemeId, Theme> = {
  chevalier: {
    id: "chevalier",
    name: "Chevalier",
    mascotName: "Loukas le Chevalier",
    greeting: "Salut ! Je suis Loukas le Chevalier. Prêt pour l'aventure au château ?",
    iconArt: "shield",
    colors: {
      primary: "#7C3AED",
      secondary: "#F59E0B",
      soft: "#EDE9FE",
      text: "#3B0764",
    },
    sky: { top: "#7DD3FC", bottom: "#E0F2FE" },
    items: [
      { art: "shield", singular: "bouclier", plural: "boucliers" },
      { art: "swords", singular: "épée", plural: "épées" },
      { art: "crown", singular: "couronne", plural: "couronnes" },
      { art: "castle", singular: "château", plural: "châteaux" },
    ],
    badgeName: "écu doré",
    badgeArt: "shield",
    challenge: { mover: "horse", target: "castle", win: "Tu as conquis le château !" },
  },
  pompier: {
    id: "pompier",
    name: "Pompier",
    mascotName: "Loukas le Pompier",
    greeting: "Salut ! Je suis Loukas le Pompier. On part en mission ensemble ?",
    iconArt: "helmet",
    colors: {
      primary: "#DC2626",
      secondary: "#FBBF24",
      soft: "#FEE2E2",
      text: "#7F1D1D",
    },
    sky: { top: "#60A5FA", bottom: "#FDE68A" },
    items: [
      { art: "fire-engine", singular: "camion", plural: "camions" },
      { art: "helmet", singular: "casque", plural: "casques" },
      { art: "extinguisher", singular: "extincteur", plural: "extincteurs" },
      { art: "fire", singular: "flamme", plural: "flammes" },
    ],
    badgeName: "médaille du courage",
    badgeArt: "medal",
    challenge: { mover: "fire-engine", target: "fire", win: "Le feu est éteint !" },
  },
  foot: {
    id: "foot",
    name: "Foot",
    mascotName: "Loukas le Footballeur",
    greeting: "Salut ! Je suis Loukas le Footballeur. On va marquer plein de buts ?",
    iconArt: "ball",
    colors: {
      primary: "#16A34A",
      secondary: "#2563EB",
      soft: "#DCFCE7",
      text: "#14532D",
    },
    sky: { top: "#3B82F6", bottom: "#BFDBFE" },
    items: [
      { art: "ball", singular: "ballon", plural: "ballons" },
      { art: "tshirt", singular: "maillot", plural: "maillots" },
      { art: "goal", singular: "but", plural: "buts" },
      { art: "trophy", singular: "trophée", plural: "trophées" },
    ],
    badgeName: "coupe des champions",
    badgeArt: "trophy",
    challenge: { mover: "ball", target: "goal", win: "BUUUT ! Tu as marqué !" },
  },
  course: {
    id: "course",
    name: "Pilote",
    mascotName: "Loukas le Pilote",
    greeting: "Salut ! Je suis Loukas le Pilote. Attache ta ceinture, on fait la course ?",
    iconArt: "racing-car",
    colors: {
      primary: "#EA580C",
      secondary: "#0EA5E9",
      soft: "#FFEDD5",
      text: "#7C2D12",
    },
    sky: { top: "#38BDF8", bottom: "#FEF3C7" },
    items: [
      { art: "racing-car", singular: "voiture", plural: "voitures" },
      { art: "checkered-flag", singular: "drapeau", plural: "drapeaux" },
      { art: "wheel", singular: "roue", plural: "roues" },
      { art: "trophy", singular: "coupe", plural: "coupes" },
    ],
    badgeName: "coupe du pilote",
    badgeArt: "checkered-flag",
    challenge: { mover: "racing-car", target: "checkered-flag", win: "Drapeau à damier ! Tu as gagné la course !" },
  },
};

export const THEME_ORDER: ThemeId[] = ["chevalier", "pompier", "foot", "course"];
